name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm

      - name: Cache Vite/Vitest transform caches
        uses: actions/cache@v4
        with:
          path: |
            node_modules/.vite
            node_modules/.vitest
          key: ${{ runner.os }}-vite-vitest-${{ hashFiles('package-lock.json', 'vite.config.ts', 'tsconfig.json') }}
          restore-keys: |
            ${{ runner.os }}-vite-vitest-

      - name: Install dependencies
        run: |
          # Ensure Linux-native optional deps for Rollup resolve correctly
          rm -f package-lock.json
          npm install --no-audit --no-fund

      - name: Run tests
        run: npm run test:run
        env:
          ROLLUP_USE_NODEJS: 'true'

      - name: Coverage
        run: npm run coverage
        env:
          ROLLUP_USE_NODEJS: 'true'
          CI_COVERAGE_PROVIDER: 'istanbul'
          CI_COVERAGE_THRESH_LINES: '70'
          CI_COVERAGE_THRESH_FUNCTIONS: '65'
          CI_COVERAGE_THRESH_STATEMENTS: '70'
          CI_COVERAGE_THRESH_BRANCHES: '45'

      - name: Upload coverage (lcov)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-lcov
          path: coverage/
